# Generated by Django 6.0.2 on 2026-04-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('preview', models.TextField(verbose_name='Краткое превью')),
                ('content', models.TextField(verbose_name='Полный текст')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Обложка')),
                ('date', models.DateField(verbose_name='Дата публикации')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликована')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
