# Generated by Django 6.0.2 on 2026-04-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_article_content_alter_article_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликована')], db_index=True, default='draft', max_length=20, verbose_name='Статус'),
        ),
    ]
