# Generated by Django 6.0.2 on 2026-05-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0005_remove_medication_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='label',
            field=models.CharField(blank=True, max_length=300, verbose_name='Метка'),
        ),
    ]
