# Generated by Django 6.0.2 on 2026-04-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_passwordresettoken_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='has_seen_welcome',
            field=models.BooleanField(default=False, verbose_name='Видел приветствие'),
        ),
    ]
