# Generated by Django 6.0.2 on 2026-05-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_default_organization_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_manage_news',
            field=models.BooleanField(default=False, verbose_name='Управление новостями'),
        ),
    ]
