# Generated by Django 6.0.2 on 2026-03-28 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_remove_question_scale_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['stage', 'order'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'ordering': ['-completed_at'], 'verbose_name': 'Результат теста', 'verbose_name_plural': 'Результаты тестов'},
        ),
        migrations.AddField(
            model_name='test',
            name='category',
            field=models.CharField(blank=True, choices=[('complex', 'Комплексная оценка болевого синдрома'), ('painad', 'PAINAD')], default='', max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('scale', 'Шкала (ползунок)'), ('single', 'Одиночный выбор'), ('multiple', 'Множественный выбор')], max_length=20, verbose_name='Тип вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='scale_labels',
            field=models.JSONField(blank=True, default=list, help_text='Пример: [{"min":0,"max":1,"label":"Нет боли"},{"min":2,"max":3,"label":"Лёгкая боль"}]', verbose_name='Подписи шкалы'),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Баллы (вес)'),
        ),
        migrations.AlterField(
            model_name='scorerange',
            name='sidebar_step',
            field=models.PositiveIntegerField(blank=True, help_text='К баллам какого шага сайдбара применяется (1=VAS, 2=DN4, 3=CSI, 4=HADS). Пусто = применяется к общей сумме всего теста.', null=True, verbose_name='Шаг сайдбара'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='status',
            field=models.CharField(choices=[('completed', 'Завершён'), ('reviewed', 'Проверен врачом')], default='completed', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='answers_data',
            field=models.JSONField(default=dict, help_text='{"q_<id>": value} — сохраняется при каждом переходе', verbose_name='Промежуточные ответы'),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='taken_by',
            field=models.ForeignKey(blank=True, help_text='Если доктор заполняет за пациента — здесь доктор, иначе сам пациент', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Проводил тест'),
        ),
    ]
