# Generated by Django 6.0.2 on 2026-03-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_add_category_to_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='category',
            field=models.CharField(blank=True, choices=[('complex', 'Комплексная оценка болевого синдрома'), ('painad', 'PAINAD'), ('ncsr', 'NCS-R')], default='', max_length=20, verbose_name='Категория'),
        ),
    ]
