# Generated by Django 6.0.2 on 2026-03-29 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_pain_duration_patient_pain_location'),
        ('tests', '0007_add_ncsr_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='testresult',
            index=models.Index(fields=['patient', '-completed_at'], name='testresult_patient_date_idx'),
        ),
        migrations.AddIndex(
            model_name='testresult',
            index=models.Index(fields=['patient', 'status'], name='testresult_patient_status_idx'),
        ),
        migrations.AddIndex(
            model_name='testsession',
            index=models.Index(fields=['patient', 'status'], name='testsession_patient_status_idx'),
        ),
        migrations.AddIndex(
            model_name='testsession',
            index=models.Index(fields=['taken_by', 'status'], name='testsession_takenby_status_idx'),
        ),
    ]
