# Generated by Django 6.0.2 on 2026-05-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_fix_hads_depression_question_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='annotation_doctor',
            field=models.TextField(blank=True, help_text='Если заполнено — показывается врачу вместо общей аннотации', verbose_name='Аннотация для врача'),
        ),
        migrations.AddField(
            model_name='stage',
            name='annotation_patient',
            field=models.TextField(blank=True, help_text='Если заполнено — показывается пациенту вместо общей аннотации', verbose_name='Аннотация для пациента'),
        ),
    ]
