# Generated by Django 6.0.2 on 2026-02-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pain_duration',
            field=models.CharField(blank=True, max_length=20, verbose_name='Длительность боли'),
        ),
        migrations.AddField(
            model_name='patient',
            name='pain_location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Локализация боли'),
        ),
    ]
