# Generated by Django 6.0.2 on 2026-04-08 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0005_remove_medication_image'),
        ('patients', '0002_patient_pain_duration_patient_pain_location'),
        ('tests', '0008_add_db_indexes'),
        ('therapy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('doctor', models.ForeignKey(limit_choices_to={'user_type': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_conclusions', to=settings.AUTH_USER_MODEL, verbose_name='Врач')),
                ('last_test_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conclusions', to='tests.testresult', verbose_name='Последний результат теста')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conclusions', to='patients.patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Заключение',
                'verbose_name_plural': 'Заключения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConclusionMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conclusion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conclusion_medications', to='patients.conclusion', verbose_name='Заключение')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_conclusions', to='medications.medication', verbose_name='Лекарство')),
            ],
            options={
                'verbose_name': 'Лекарство в заключении',
                'verbose_name_plural': 'Лекарства в заключениях',
                'unique_together': {('conclusion', 'medication')},
            },
        ),
        migrations.AddField(
            model_name='conclusion',
            name='medications',
            field=models.ManyToManyField(blank=True, through='patients.ConclusionMedication', to='medications.medication', verbose_name='Лекарства'),
        ),
        migrations.CreateModel(
            name='ConclusionTherapy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conclusion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conclusion_therapies', to='patients.conclusion', verbose_name='Заключение')),
                ('therapy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_conclusions', to='therapy.therapy', verbose_name='Терапия')),
            ],
            options={
                'verbose_name': 'Мероприятие в заключении',
                'verbose_name_plural': 'Мероприятия в заключениях',
                'unique_together': {('conclusion', 'therapy')},
            },
        ),
        migrations.AddField(
            model_name='conclusion',
            name='therapies',
            field=models.ManyToManyField(blank=True, through='patients.ConclusionTherapy', to='therapy.therapy', verbose_name='Реабилитационные мероприятия'),
        ),
    ]
