# Generated by Django 6.0.2 on 2026-04-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_conclusion_conclusionmedication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conclusionmedication',
            name='custom_scheme',
            field=models.TextField(blank=True, verbose_name='Схема назначения (редактированная)'),
        ),
        migrations.AddField(
            model_name='conclusiontherapy',
            name='custom_scheme',
            field=models.TextField(blank=True, verbose_name='Схема назначения (редактированная)'),
        ),
    ]
