# Generated by Django 6.0.2 on 2026-05-09 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_organization_and_doctorprofile_fk'),
        ('patients', '0004_conclusion_custom_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='accounts.organization', verbose_name='Учреждение'),
        ),
    ]
