# Generated by Django 6.0.2 on 2026-05-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patient_organization_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата архивации'),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Архивирован'),
        ),
        migrations.AddField(
            model_name='patient',
            name='scheduled_deletion_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Плановое физическое удаление'),
        ),
    ]
