# Generated by Django 6.0.2 on 2026-04-05 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Therapy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('therapy_type', models.CharField(blank=True, max_length=100, verbose_name='Тип')),
                ('prescription_scheme', models.TextField(blank=True, verbose_name='Схема назначения')),
                ('clinical_goal', models.TextField(blank=True, verbose_name='Клиническая цель')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('created_by', models.ForeignKey(limit_choices_to={'user_type': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_therapies', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Терапия',
                'verbose_name_plural': 'Терапии',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TherapyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapy_notes', to=settings.AUTH_USER_MODEL, verbose_name='Врач')),
                ('therapy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_notes', to='therapy.therapy', verbose_name='Терапия')),
            ],
            options={
                'verbose_name': 'Примечание к терапии',
                'verbose_name_plural': 'Примечания к терапиям',
                'unique_together': {('therapy', 'doctor')},
            },
        ),
    ]
